---

- name: Converge
  hosts: grp_targets
  module_defaults:
    ansible.builtin.setup:
      gather_subset: ['distribution']
  gather_facts: true

  vars:
    odoo:
      hostnames: 'odoo.test.ansibleguy.net'

  roles:
    - ansibleguy.sw_odoo_community
