---

- name: Odoo | Showing debug info - user provided config
  ansible.builtin.debug:
    var: odoo
  when: debug | bool

- name: Odoo | Showing debug info - running config
  ansible.builtin.debug:
    var: ODOO_CONFIG
  when: debug | bool

- name: Odoo | Install dependencies
  ansible.builtin.apt:
    name: ['curl', 'gpg', 'zip']
    state: present

- name: Odoo | Repository key
  ansible.builtin.shell: |
    set -o pipefail
    curl https://nightly.odoo.com/odoo.key |
    gpg --dearmor -o /usr/share/keyrings/odoo-archive-keyring.gpg
  args:
    creates: '/usr/share/keyrings/odoo-archive-keyring.gpg'
    executable: '/bin/bash'
  register: odoo_repo_key

- name: Odoo | Fail if repository-key fingerprint does not match
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gpg --show-keys --with-fingerprint --with-colons /usr/share/keyrings/odoo-archive-keyring.gpg 2>/dev/null | grep -m 1 fpr | awk -F: '{print $10}'
  args:
    executable: /bin/bash
  when: odoo_repo_key.changed
  register: odoo_repo_key_fp
  changed_when: odoo_repo_key_fp.rc != 0
  failed_when: >
    odoo_repo_key_fp.failed or
    odoo_repo_key_fp.stdout.strip() != ODOO_CONFIG.apt_gpg_key_fingerprint

- name: Odoo | Community Repository
  ansible.builtin.copy:
    content: |
      # ansible_managed
      # ansibleguy.sw_odoo_community
      deb [signed-by=/usr/share/keyrings/odoo-archive-keyring.gpg] https://nightly.odoo.com/{{ ODOO_CONFIG.version }}/nightly/deb/ ./
    dest: '/etc/apt/sources.list.d/odoo.list'
    mode: '0644'
  when: not ODOO_CONFIG.enterprise | bool

- name: Odoo | Repository
  ansible.builtin.copy:
    content: |
      # ansible_managed
      # ansibleguy.sw_odoo_community
      # deb [signed-by=/usr/share/keyrings/odoo-archive-keyring.gpg] https://nightly.odoo.com/{{ ODOO_CONFIG.version }}/nightly/deb/ ./
    dest: '/etc/apt/sources.list.d/odoo.list'
    mode: '0644'
  when: ODOO_CONFIG.enterprise | bool

- name: Odoo | Install database
  ansible.builtin.apt:
    name: ['postgresql', 'postgresql-client']
    state: present
  when: ODOO_CONFIG.manage.database | bool

- name: Odoo | Install
  ansible.builtin.apt:
    name: ['odoo', 'python3-xlwt']
    state: present
    update_cache: true
  register: odoo_installed
  when: not ODOO_CONFIG.enterprise | bool

- name: Odoo | Adding addons directory
  ansible.builtin.file:
    path: "{{ ODOO_CONFIG.conf.addons_path }}"
    mode: '0750'
    state: directory
    owner: 'root'
    group: 'odoo'

- name: Odoo | Generate Admin-Password Hash
  ansible.builtin.command: |
    python3 -c
    "from os import environ;
    from passlib.context import CryptContext;
    print(CryptContext(['pbkdf2_sha512']).hash(environ['SECRET']))"
  environment:
    SECRET: "{{ ODOO_CONFIG.conf.admin_passwd }}"
  register: odoo_admin_pwd_hash
  no_log: true
  changed_when: false

- name: Odoo | Generate Database-Password Hash
  ansible.builtin.command: |
    python3 -c
    "from os import environ;
    from passlib.context import CryptContext;
    print(CryptContext(['pbkdf2_sha512']).hash(environ['SECRET']))"
  environment:
    SECRET: "{{ ODOO_CONFIG.conf.db_password }}"
  register: odoo_db_pwd_hash
  no_log: true
  changed_when: false

- name: Odoo | Adding config
  ansible.builtin.template:
    src: 'templates/etc/odoo/odoo.conf.j2'
    dest: '/etc/odoo/odoo.conf'
    owner: 'root'
    group: 'odoo'
    mode: '0640'
  changed_when: false  # password hashes will always change..

- name: Odoo | Adding service-override directory
  ansible.builtin.file:
    path: '/etc/systemd/system/odoo.service.d'
    mode: '0750'
    state: directory

- name: Odoo | Adding service-override
  ansible.builtin.template:
    src: 'templates/etc/systemd/system/odoo.service.d/override.conf.j2'
    dest: '/etc/systemd/system/odoo.service.d/override.conf'
    mode: '0640'

- name: Odoo | Starting/Enabling database
  ansible.builtin.systemd:
    name: 'postgresql.service'
    enabled: true
    state: started
  when: ODOO_CONFIG.manage.database | bool

- name: Odoo | Starting/Enabling service
  ansible.builtin.systemd:
    name: 'odoo.service'
    enabled: true
    state: started
    daemon_reload: true
  when: not ODOO_CONFIG.enterprise | bool

- name: Odoo | Adding backup directory
  ansible.builtin.file:
    path: "{{ ODOO_CONFIG.backup.path }}"
    mode: '0750'
    state: directory
    owner: 'root'
    group: 'postgres'
  when: ODOO_CONFIG.backup.enable | bool

- name: Odoo | Adding backup script and service
  ansible.builtin.template:
    src: "templates/{{ item.s }}.j2"
    dest: "{{ item.s }}"
    mode: "{{ item.m | default('0644') }}"
  loop:
    - {s: '/etc/systemd/system/odoo-backup.service'}
    - {s: '/etc/systemd/system/odoo-backup.timer'}
    - {s: '/usr/local/bin/odoo_backup.sh', m: '0750'}
  when: ODOO_CONFIG.backup.enable | bool

- name: Odoo | Starting/Enabling backup timer
  ansible.builtin.systemd:
    name: 'odoo-backup.timer'
    enabled: true
    state: started
    daemon_reload: true
  when: ODOO_CONFIG.backup.enable | bool

- name: Odoo | Stopping/Disabling backup timer
  ansible.builtin.systemd:
    name: 'odoo-backup.timer'
    enabled: false
    state: stopped
  register: odoo_backup_dis
  failed_when:
    - odoo_backup_dis.failed
    - "'Could not find the requested service' not in odoo_backup_dis.msg"
  when: not ODOO_CONFIG.backup.enable | bool

- name: Odoo | Webserver
  ansible.builtin.include_role:
    name: ansibleguy.infra_nginx
  when: ODOO_CONFIG.manage.webserver | bool
  vars:
    # see: https://www.odoo.com/documentation/17.0/administration/on_premise/deploy.html#https
    odoo_nginx_config_overrides:
      domain: "{{ ODOO_CONFIG.hostnames | ensure_list | first }}"
      aliases: "{{ ODOO_CONFIG.hostnames }}"
      proxy:
        proto: 'http'
        port: 8069
      options:
        client_max_body_size: '500m'
        client_body_timeout: '30s'
        client_body_in_file_only: 'clean'
        sendfile: 'on'
        send_timeout: '600s'
        keepalive_timeout: '300'
      headers:
        'X-Frame-Options': 'SAMEORIGIN'
      global_additions:
        - "map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
          }"
      config_additions:
        - 'location /websocket {
          proxy_pass http://127.0.0.1:8072;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
          proxy_cookie_flags session_id samesite=lax secure;
          }'
        - 'gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript'
        - 'gzip on'
      config_additions_root:
        - 'proxy_redirect off'
        - 'proxy_cookie_flags session_id samesite=lax secure'
        - 'proxy_hide_header X-Frame-Options'
      security:
        restrict_methods: false
    nginx:
      sites:
        odoo: "{{ ODOO_CONFIG.nginx | combine(odoo_nginx_config_overrides, recursive=true) }}"

  tags: [webserver]
  args:
    apply:
      tags: [webserver]

- name: Odoo | Displaying auto-generated credentials
  ansible.builtin.debug:
    msg: >
      "Make sure to update your 'odoo.db.pwd' and 'odoo.admin_pwd' if not configured!
      Admin/Master: '{{ ODOO_CONFIG.admin_pwd }}',
      Database: '{{ ODOO_CONFIG.db.pwd }}'"
  when: >
    odoo_installed.changed and
    (
    ODOO_CONFIG.admin_pwd == defaults_odoo.admin_pwd or
    ODOO_CONFIG.db.pwd == defaults_odoo.db.pwd
    )
